### ISSUE TITLE
Opening short links

### ISSUE THREAD

**Issue by JackPlaysGames0510** [CokePokes/YoutubeExtensions#2]
When opening shorts links it goes to a channel called null

**Comment by CokePokes** [comment]
Short links aren’t supported. But in the newest version, they should give an error instead of going to null. 

I’ll see if I can get the redirect before launching those.

**Comment by CokePokes** [comment]
This was fixed in version 1.2

**Comment by JackPlaysGames0510** [comment]
hi I still have the problem where it still goes to the channel called null
